# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Kani CI
on: [push, pull_request]

jobs:
  bookrunner:
    runs-on: macos-10.15
    permissions:
      contents: write
    steps:
      - name: Checkout Kani
        uses: actions/checkout@v2

      - name: Build Kani
        uses: ./.github/actions/build
        with:
            os: macos-10.15

      - name: Install book runner dependencies
        run: |
          brew install litani
          python3 -m pip install bs4

      - name: Generate book runner report
        run: cargo run -p bookrunner
        env:
            DOC_RUST_LANG_ORG_CHANNEL: nightly

      - name: Print book runner text results
        run: cat build/output/latest/html/bookrunner.txt

      - name: Detect unpexpected book runner failures
        run: ./scripts/ci/detect_bookrunner_failures.sh build/output/latest/html/bookrunner.txt

      # On one OS only, build the documentation, too.
      - name: Build Documentation
        run: ./docs/build-docs.sh
